import type { DemographicCategory } from "@prisma/client";

export const DEMOGRAPHIC_MATRIX: Record<DemographicCategory, string[]> = {
  SEX: ["Men", "Women", "Non-binary individuals"],
  MARITAL_STATUS: ["Single", "Married", "Divorced/Separated", "Widowed"],
  SEXUAL_ORIENTATION: ["Heterosexual", "LGBTQ+"],
  RELIGION: [
    "Christian",
    "Muslim",
    "Jewish",
    "Hindu",
    "Buddhist",
    "Non-religious",
    "Other faith",
  ],
  ETHNICITY: [
    "White",
    "Black/African American",
    "Hispanic/Latino",
    "Asian American",
    "Native American/Indigenous",
    "Pacific Islander",
    "Multiracial",
  ],
  SALARY_BRACKET: [
    "Under $25k",
    "$25k-$50k",
    "$50k-$75k",
    "$75k-$100k",
    "$100k-$150k",
    "$150k-$250k",
    "Over $250k",
  ],
  US_STATE: [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
    "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
    "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York",
    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming", "District of Columbia",
  ],
  POLITICAL_AFFILIATION: [
    "Democrat",
    "Republican",
    "Independent",
    "Non-affiliated",
  ],
};

export const LOADED_WORDS = [
  "controversial",
  "radical",
  "extreme",
  "dangerous",
  "historic",
  "unprecedented",
  "disastrous",
  "brilliant",
  "terrible",
  "amazing",
  "horrible",
  "wonderful",
  "catastrophic",
  "groundbreaking",
  "shocking",
  "outrageous",
  "disgraceful",
  "courageous",
  "reckless",
  "visionary",
];

export const POLICY_KEYWORDS = [
  "executive order",
  "regulation",
  "agency rule",
  "appointment",
  "federal register",
  "white house",
  "administration policy",
  "legislation",
  "bill signed",
  "presidential",
  "memorandum",
  "proclamation",
  "cabinet",
  "department of",
  "tariff",
  "immigration",
  "border",
  "trade",
  "sanctions",
  "federal agency",
];

export const ITEMS_PER_PAGE = 20;
